//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlackAlerter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class @default : global::System.Configuration.ApplicationSettingsBase {
        
        private static @default defaultInstance = ((@default)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new @default())));
        
        public static @default Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APIKey")]
        public string HoistAPIKey {
            get {
                return ((string)(this["HoistAPIKey"]));
            }
            set {
                this["HoistAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XeroConnectorKey")]
        public string XeroConnectorKey {
            get {
                return ((string)(this["XeroConnectorKey"]));
            }
            set {
                this["XeroConnectorKey"] = value;
            }
        }
    }
}
